[Match]
Distribution=fedora
Release=43

[Build]
SandboxTrees=
    repos/patrickl-wine-tkg.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:patrickl:wine-tkg.repo
    repos/timlau-audio.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:timlau:audio.repo

[Distribution]
Repositories=
    copr:copr.fedorainfracloud.org:patrickl:wine-tkg
    copr:copr.fedorainfracloud.org:timlau:audio

[Content]
WithRecommends=false
Packages=
    AIDA-X
    AIDA-X-clap
    AIDA-X-lv2
    AIDA-X-vst3
    BYOD
    BYOD-clap
    BYOD-lv2
    BYOD-vst3
    Crypt2
    Crypt2-clap
    Crypt2-lv2
    Crypt2-vst3
    INTERSECT
    INTERSECT-clap
    INTERSECT-lv2
    INTERSECT-vst3
    Loopino
    Loopino-clap
    LostAndFoundPiano
    LostAndFoundPiano-clap
    LostAndFoundPiano-lv2
    LostAndFoundPiano-vst3
    OB-Xf
    OB-Xf-clap
    OB-Xf-lv2
    OB-Xf-vst3
    Vaporizer2
    Vaporizer2-clap
    Vaporizer2-lv2
    Vaporizer2-vst3
    Wavetable
    Wavetable-clap
    Wavetable-lv2
    Wavetable-vst3
    dexed
    dexed-clap
    dexed-vst3
    dragonfly-reverb
    dragonfly-reverb-clap
    dragonfly-reverb-lv2
    dragonfly-reverb-vst3
    jdrummer
    jdrummer-clap
    jdrummer-lv2
    jdrummer-vst3
    libcurl-gnutls
    neural-amp-modeler-lv2
    odin2
    odin2-lv2
    odin2-vst3
    realtime-setup
    wine.x86_64
    winetricks
    yabridge
    yabridgectl
