[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/wojnilowicz.ungoogled-chromium.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:wojnilowicz.ungoogled-chromium.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:wojnilowicz.ungoogled-chromium

[Content]
WithRecommends=false
Packages=
    ungoogled-chromium
