[Match]
Distribution=fedora

# https://gitlab.com/redhat/centos-stream/containers/bootc/-/blob/c${CENTOS_VERSION}s/edge/manifest.yaml?ref_type=heads
[Content]
WithRecommends=true
VolatilePackages=
    systemd-container
    systemd-oomd-defaults
    systemd-pam
    systemd-resolved

Packages=
    7zip
    acl
    attr
    bash-completion
    bind-utils
    bzip2
    criu
    criu-libs
    crun
    cryptsetup
    dosfstools
    e2fsprogs
    fd-find
    fwupd
    git-core
    hostname
    iproute
    iproute-tc
    iptables-nft
    jq
    less
    logrotate
    lsof
    lvm2
    neovim
    net-tools
    nftables
    nvme-cli
    openssl
    openssh
    ripgrep
    passwd
    rpm-plugin-selinux
    rsync
    shadow-utils
    socat
    stalld
    sudo
    tar
    tzdata
    xfsprogs
    zoxide
    zram-generator
    zsh
    zstd

# From Miasma OS
    realtime-setup
    ardour9
    qtractor
    carla
    lsp-plugins-vst
    lsp-plugins-clap
    zam-plugins
    calf
    guitarix
    sooperlooper
    musescore
    hydrogen
    yoshimi
    jack-audio-connection-kit
    jack-audio-connection-kit-dbus
    qjackctl
    ffado
    pavucontrol
    qsynth
    fluidsynth
    fluid-soundfont-gm
    timidity++
    qmidiarp
    vmpk
    harmonyseq
    bristol
    synthv1
    drumkv1
    rakarrack
    lsp-plugins-lv2
    lv2-ll-plugins
    lv2-swh-plugins
    lv2-vocoder-plugins
    lv2-zynadd-plugins
    lv2dynparam
    lv2-abGate
    lv2-samplv1
    lv2-synthv1
    lv2-drumkv1
    lv2-newtonator
    lv2-x42-plugins
    lv2-sorcer
    lv2-fabla
    lsp-plugins-lv2
    lv2-carla

